### ISSUE TITLE
Small typos in the presentation

### ISSUE THREAD

**Issue by csarnataro** [eddiejaoude/opensource-deployment-presenation#36]
Two small typos exist in the presentation at page:
https://eddiejaoude.github.io/opensource-deployment-presenation/#/1/8
- INVOVLED instead of INVOLVED
- Contibute instead of Contribute

I'm going to send a PR soon with these 2 typos fixed :)

BTW, the repo name itself contains a typo (presenation instead of presentation) but I think this cannot be fixed through a simple pull request.

**Comment by eddiejaoude** [comment]
PR merged, thank you 👍 

> BTW, the repo name itself contains a typo (presenation instead of presentation) but I think this cannot be fixed through a simple pull request.

OMG yes you are right!! I will fix it 🤓
